name = "practice"
[build]
assets = [
    "frontend/dist/*",
    "config/production.yaml",
    "assets/*",
    ".env",
]

[deploy]
include = [
    "frontend/dist/*",
    "config/production.yaml",
    "assets/*",
    ".env",
]